/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/openshift/cluster-api/pkg/apis/machine/v1beta1"
	scheme "github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SmartMachineSetsGetter has a method to return a SmartMachineSetInterface.
// A group's client should implement this interface.
type SmartMachineSetsGetter interface {
	SmartMachineSets(namespace string) SmartMachineSetInterface
}

// SmartMachineSetInterface has methods to work with SmartMachineSet resources.
type SmartMachineSetInterface interface {
	Create(*v1beta1.SmartMachineSet) (*v1beta1.SmartMachineSet, error)
	Update(*v1beta1.SmartMachineSet) (*v1beta1.SmartMachineSet, error)
	UpdateStatus(*v1beta1.SmartMachineSet) (*v1beta1.SmartMachineSet, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.SmartMachineSet, error)
	List(opts v1.ListOptions) (*v1beta1.SmartMachineSetList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.SmartMachineSet, err error)
	SmartMachineSetExpansion
}

// smartMachineSets implements SmartMachineSetInterface
type smartMachineSets struct {
	client rest.Interface
	ns     string
}

// newSmartMachineSets returns a SmartMachineSets
func newSmartMachineSets(c *MachineV1beta1Client, namespace string) *smartMachineSets {
	return &smartMachineSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the smartMachineSet, and returns the corresponding smartMachineSet object, and an error if there is any.
func (c *smartMachineSets) Get(name string, options v1.GetOptions) (result *v1beta1.SmartMachineSet, err error) {
	result = &v1beta1.SmartMachineSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("smartmachinesets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SmartMachineSets that match those selectors.
func (c *smartMachineSets) List(opts v1.ListOptions) (result *v1beta1.SmartMachineSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.SmartMachineSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("smartmachinesets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested smartMachineSets.
func (c *smartMachineSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("smartmachinesets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a smartMachineSet and creates it.  Returns the server's representation of the smartMachineSet, and an error, if there is any.
func (c *smartMachineSets) Create(smartMachineSet *v1beta1.SmartMachineSet) (result *v1beta1.SmartMachineSet, err error) {
	result = &v1beta1.SmartMachineSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("smartmachinesets").
		Body(smartMachineSet).
		Do().
		Into(result)
	return
}

// Update takes the representation of a smartMachineSet and updates it. Returns the server's representation of the smartMachineSet, and an error, if there is any.
func (c *smartMachineSets) Update(smartMachineSet *v1beta1.SmartMachineSet) (result *v1beta1.SmartMachineSet, err error) {
	result = &v1beta1.SmartMachineSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("smartmachinesets").
		Name(smartMachineSet.Name).
		Body(smartMachineSet).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *smartMachineSets) UpdateStatus(smartMachineSet *v1beta1.SmartMachineSet) (result *v1beta1.SmartMachineSet, err error) {
	result = &v1beta1.SmartMachineSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("smartmachinesets").
		Name(smartMachineSet.Name).
		SubResource("status").
		Body(smartMachineSet).
		Do().
		Into(result)
	return
}

// Delete takes name of the smartMachineSet and deletes it. Returns an error if one occurs.
func (c *smartMachineSets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("smartmachinesets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *smartMachineSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("smartmachinesets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched smartMachineSet.
func (c *smartMachineSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.SmartMachineSet, err error) {
	result = &v1beta1.SmartMachineSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("smartmachinesets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
